/**
 * assessments.ts
 * 16 Assessments with 112+ Curated Assessment Questions across Conceptual,
 * Debugging, Code Reasoning, and Output Prediction for the Initial Learning Catalog.
 */

export interface CatalogAssessmentQuestion {
  id: string;
  assessmentId: string;
  skillId: string;
  question: string;
  options: string[];
  correctAnswer: string;
  explanation: string;
  difficulty: 'easy' | 'medium' | 'hard';
  points: number;
  active: boolean;
}

export interface CatalogAssessment {
  id: string;
  skillId: string;
  title: string;
  description: string;
  difficulty: string;
  totalQuestions: number;
  passingScore: number;
  active: boolean;
  questions: CatalogAssessmentQuestion[];
}

export const CATALOG_ASSESSMENTS: CatalogAssessment[] = [
  // ── 1. HTML Fundamentals ──────────────────────────────────────────────────
  {
    id: "assess-html-fundamentals",
    skillId: "html-css",
    title: "HTML Fundamentals & Semantic Web Assessment",
    description: "Evaluate structural HTML knowledge, semantic tag hierarchy, forms, accessibility, and modern HTML5 specifications.",
    difficulty: "Mixed",
    totalQuestions: 7,
    passingScore: 70,
    active: true,
    questions: [
      {
        id: "q-html-1",
        assessmentId: "assess-html-fundamentals",
        skillId: "html-css",
        question: "Which HTML5 element should be used to wrap autonomous, self-contained syndicatable content such as a blog post or news story?",
        options: ["<section>", "<div>", "<article>", "<aside>"],
        correctAnswer: "<article>",
        explanation: "<article> represents an independent, self-contained composition in a document.",
        difficulty: "easy",
        points: 10,
        active: true,
      },
      {
        id: "q-html-2",
        assessmentId: "assess-html-fundamentals",
        skillId: "html-css",
        question: "What is the primary accessibility benefit of linking a <label> to an <input> using the 'for' and 'id' attributes?",
        options: [
          "It automatically applies CSS theme styling",
          "Clicking the label focuses the input and screen readers announce the label text",
          "It encrypts the input value before submission",
          "It prevents form submission if empty"
        ],
        correctAnswer: "Clicking the label focuses the input and screen readers announce the label text",
        explanation: "The for-id association establishes programmatic linkage for assistive technologies and improves tap target size.",
        difficulty: "easy",
        points: 10,
        active: true,
      },
      {
        id: "q-html-3",
        assessmentId: "assess-html-fundamentals",
        skillId: "html-css",
        question: "What happens if an <img> tag is missing an 'alt' attribute?",
        options: [
          "The browser refuses to load the image",
          "Screen readers may announce the entire raw image URL or file path, degrading accessibility",
          "The HTML validator automatically replaces it with the filename",
          "The image renders in black and white"
        ],
        correctAnswer: "Screen readers may announce the entire raw image URL or file path, degrading accessibility",
        explanation: "Without an alt attribute, screen readers cannot communicate the content of the image and often fall back to reading the noisy file path.",
        difficulty: "medium",
        points: 10,
        active: true,
      },
      {
        id: "q-html-4",
        assessmentId: "assess-html-fundamentals",
        skillId: "html-css",
        question: "Which doctype declaration is required for modern HTML5 documents?",
        options: ["<!DOCTYPE html5>", "<!DOCTYPE HTML PUBLIC>", "<!DOCTYPE html>", "<?xml version=\"1.0\"?>"],
        correctAnswer: "<!DOCTYPE html>",
        explanation: "<!DOCTYPE html> is the concise, case-insensitive doctype required to trigger standard rendering mode in modern browsers.",
        difficulty: "easy",
        points: 10,
        active: true,
      },
      {
        id: "q-html-5",
        assessmentId: "assess-html-fundamentals",
        skillId: "html-css",
        question: "Which attribute should be added to an <input> tag to indicate that the user cannot submit the form without providing a value?",
        options: ["validate=\"true\"", "required", "mandatory", "checked"],
        correctAnswer: "required",
        explanation: "The boolean 'required' attribute leverages native browser form constraint validation.",
        difficulty: "easy",
        points: 10,
        active: true,
      },
      {
        id: "q-html-6",
        assessmentId: "assess-html-fundamentals",
        skillId: "html-css",
        question: "In responsive web design, what is the role of <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">?",
        options: [
          "It forces the website into desktop mode on smartphones",
          "It instructs the mobile browser to set the viewport width to the device screen width without auto-scaling",
          "It downloads higher resolution retina images",
          "It pre-caches mobile CSS files"
        ],
        correctAnswer: "It instructs the mobile browser to set the viewport width to the device screen width without auto-scaling",
        explanation: "The viewport meta tag establishes the virtual layout viewport size matching the physical device width at 1:1 scale.",
        difficulty: "medium",
        points: 10,
        active: true,
      },
      {
        id: "q-html-7",
        assessmentId: "assess-html-fundamentals",
        skillId: "html-css",
        question: "Debugging: Why is nesting an <a> tag inside another <a> tag invalid in HTML5?",
        options: [
          "Interactive elements cannot contain other interactive descendants according to HTML specifications",
          "Browsers only support up to 3 links per page",
          "The CSS cascade cannot calculate color for nested links",
          "It causes an infinite redirect loop"
        ],
        correctAnswer: "Interactive elements cannot contain other interactive descendants according to HTML specifications",
        explanation: "Interactive content elements like <a> and <button> must never contain other interactive content descendants.",
        difficulty: "hard",
        points: 10,
        active: true,
      },
    ],
  },

  // ── 2. CSS Fundamentals ───────────────────────────────────────────────────
  {
    id: "assess-css-fundamentals",
    skillId: "html-css",
    title: "CSS Fundamentals, Box Model & Layouts Assessment",
    description: "Assess comprehension of specificity, the box model, Flexbox axes, and CSS Grid layout algorithms.",
    difficulty: "Mixed",
    totalQuestions: 7,
    passingScore: 70,
    active: true,
    questions: [
      {
        id: "q-css-1",
        assessmentId: "assess-css-fundamentals",
        skillId: "html-css",
        question: "Under 'box-sizing: border-box', if an element has width: 200px, padding: 20px, and border: 5px, what is its total rendered outer width?",
        options: ["250px", "200px", "225px", "240px"],
        correctAnswer: "200px",
        explanation: "In border-box sizing, padding and border are absorbed inside the declared 200px width.",
        difficulty: "easy",
        points: 10,
        active: true,
      },
      {
        id: "q-css-2",
        assessmentId: "assess-css-fundamentals",
        skillId: "html-css",
        question: "Which selector has the highest CSS specificity?",
        options: ["nav.main-nav ul li a", "#header .nav-item", "body header nav a", ".nav-link.active"],
        correctAnswer: "#header .nav-item",
        explanation: "An ID selector (#header) has a specificity of (0,1,0,0), outweighing any number of class or element selectors.",
        difficulty: "medium",
        points: 10,
        active: true,
      },
      {
        id: "q-css-3",
        assessmentId: "assess-css-fundamentals",
        skillId: "html-css",
        question: "In a flex container with 'flex-direction: row', which property aligns flex items along the cross axis (vertically)?",
        options: ["justify-content", "align-items", "flex-wrap", "content-align"],
        correctAnswer: "align-items",
        explanation: "For flex-direction: row, the main axis is horizontal (justify-content) and the cross axis is vertical (align-items).",
        difficulty: "easy",
        points: 10,
        active: true,
      },
      {
        id: "q-css-4",
        assessmentId: "assess-css-fundamentals",
        skillId: "html-css",
        question: "What does 'grid-template-columns: repeat(auto-fit, minmax(250px, 1fr))' accomplish?",
        options: [
          "Creates fixed 250px columns that cause horizontal scroll",
          "Creates an intrinsically responsive grid that automatically wraps columns to new rows without media queries",
          "Forces exactly 4 columns on all screens",
          "Centers a single column on the screen"
        ],
        correctAnswer: "Creates an intrinsically responsive grid that automatically wraps columns to new rows without media queries",
        explanation: "auto-fit with minmax calculates the maximum number of >= 250px columns that fit into available space and stretches them with 1fr.",
        difficulty: "hard",
        points: 10,
        active: true,
      },
      {
        id: "q-css-5",
        assessmentId: "assess-css-fundamentals",
        skillId: "html-css",
        question: "What is the difference between 'display: none' and 'visibility: hidden'?",
        options: [
          "display: none removes the element from document layout flow; visibility: hidden hides it while preserving its physical space",
          "There is no difference",
          "visibility: hidden removes the element from the DOM completely",
          "display: none is only supported in modern browsers"
        ],
        correctAnswer: "display: none removes the element from document layout flow; visibility: hidden hides it while preserving its physical space",
        explanation: "display: none collapses the element box entirely, whereas visibility: hidden keeps the box geometry in layout.",
        difficulty: "medium",
        points: 10,
        active: true,
      },
      {
        id: "q-css-6",
        assessmentId: "assess-css-fundamentals",
        skillId: "html-css",
        question: "What happens when you apply 'position: absolute' to an element?",
        options: [
          "It is positioned relative to the viewport always",
          "It is removed from standard document flow and positioned relative to its closest positioned ancestor",
          "It behaves exactly like position: fixed",
          "It centers itself automatically"
        ],
        correctAnswer: "It is removed from standard document flow and positioned relative to its closest positioned ancestor",
        explanation: "Absolute elements position against the nearest ancestor having a position other than 'static'.",
        difficulty: "medium",
        points: 10,
        active: true,
      },
      {
        id: "q-css-7",
        assessmentId: "assess-css-fundamentals",
        skillId: "html-css",
        question: "Why should '!important' be avoided in routine CSS authoring?",
        options: [
          "It breaks browser rendering engines",
          "It subverts the natural cascade and makes rules difficult to maintain and override in large codebases",
          "It increases HTTP bundle download size significantly",
          "It is deprecated in CSS3"
        ],
        correctAnswer: "It subverts the natural cascade and makes rules difficult to maintain and override in large codebases",
        explanation: "!important overrides normal specificity, leading to cascading specificity wars and maintenance debt.",
        difficulty: "easy",
        points: 10,
        active: true,
      },
    ],
  },

  // ── 3. JavaScript Fundamentals ────────────────────────────────────────────
  {
    id: "assess-js-fundamentals",
    skillId: "javascript",
    title: "JavaScript Fundamentals & Core Language Assessment",
    description: "Measure understanding of types, closures, strict equality, array methods, and scope.",
    difficulty: "Mixed",
    totalQuestions: 7,
    passingScore: 70,
    active: true,
    questions: [
      {
        id: "q-js-1",
        assessmentId: "assess-js-fundamentals",
        skillId: "javascript",
        question: "What is the output of 'console.log(typeof NaN)'?",
        options: ["\"undefined\"", "\"nan\"", "\"number\"", "\"string\""],
        correctAnswer: "\"number\"",
        explanation: "In JavaScript, NaN represents an invalid numerical operation result, but its primitive data type is 'number'.",
        difficulty: "medium",
        points: 10,
        active: true,
      },
      {
        id: "q-js-2",
        assessmentId: "assess-js-fundamentals",
        skillId: "javascript",
        question: "What is the output of 'console.log([] == ![])' in JavaScript?",
        options: ["true", "false", "TypeError", "undefined"],
        correctAnswer: "true",
        explanation: "![] evaluates to false. [] == false coerces both sides to numbers: 0 == 0, resulting in true.",
        difficulty: "hard",
        points: 10,
        active: true,
      },
      {
        id: "q-js-3",
        assessmentId: "assess-js-fundamentals",
        skillId: "javascript",
        question: "Which statement accurately describes a closure in JavaScript?",
        options: [
          "A block statement wrapped in braces",
          "A function bundled with references to its surrounding lexical state (lexical environment)",
          "A technique to terminate infinite loops",
          "A method to make variables immutable"
        ],
        correctAnswer: "A function bundled with references to its surrounding lexical state (lexical environment)",
        explanation: "A closure retains access to variables declared in its outer scope even after the outer function has executed.",
        difficulty: "medium",
        points: 10,
        active: true,
      },
      {
        id: "q-js-4",
        assessmentId: "assess-js-fundamentals",
        skillId: "javascript",
        question: "How does 'const' behave when assigned to an Object in JavaScript?",
        options: [
          "The object becomes completely frozen and its properties cannot be changed",
          "The variable identifier cannot be reassigned to a new reference, but object properties can still be mutated",
          "It throws a syntax error because const is only for primitive types",
          "Properties can only be deleted, not added"
        ],
        correctAnswer: "The variable identifier cannot be reassigned to a new reference, but object properties can still be mutated",
        explanation: "const enforces immutable binding of the reference, not shallow or deep immutability of the referenced object.",
        difficulty: "easy",
        points: 10,
        active: true,
      },
      {
        id: "q-js-5",
        assessmentId: "assess-js-fundamentals",
        skillId: "javascript",
        question: "What does Array.prototype.reduce() return if no initialValue is provided?",
        options: [
          "An empty array",
          "Undefined",
          "The first element of the array is used as the initial accumulator, and iteration starts at index 1",
          "0"
        ],
        correctAnswer: "The first element of the array is used as the initial accumulator, and iteration starts at index 1",
        explanation: "When initialValue is omitted, reduce() treats array[0] as the initial accumulator.",
        difficulty: "medium",
        points: 10,
        active: true,
      },
      {
        id: "q-js-6",
        assessmentId: "assess-js-fundamentals",
        skillId: "javascript",
        question: "What does 'this' refer to inside an arrow function?",
        options: [
          "The element triggering the event",
          "The global window object always",
          "The 'this' value of the enclosing lexical scope",
          "Undefined"
        ],
        correctAnswer: "The 'this' value of the enclosing lexical scope",
        explanation: "Arrow functions do not have their own 'this' binding; they resolve 'this' lexically from the outer enclosing scope.",
        difficulty: "easy",
        points: 10,
        active: true,
      },
      {
        id: "q-js-7",
        assessmentId: "assess-js-fundamentals",
        skillId: "javascript",
        question: "What is the key difference between 'let' and 'var'?",
        options: [
          "'let' is block-scoped and cannot be accessed before declaration (temporal dead zone); 'var' is function-scoped and hoisted with undefined",
          "'var' is block-scoped while 'let' is function-scoped",
          "There is no difference in ES6",
          "'let' cannot be reassigned"
        ],
        correctAnswer: "'let' is block-scoped and cannot be accessed before declaration (temporal dead zone); 'var' is function-scoped and hoisted with undefined",
        explanation: "let provides lexical block scoping and TDZ protection against accidental premature access.",
        difficulty: "easy",
        points: 10,
        active: true,
      },
    ],
  },

  // ── 4. DOM and Events ─────────────────────────────────────────────────────
  {
    id: "assess-dom-events",
    skillId: "javascript",
    title: "DOM Manipulation & Event Architecture Assessment",
    description: "Evaluate knowledge of tree traversal, event propagation (bubbling vs capture), and event delegation.",
    difficulty: "Mixed",
    totalQuestions: 7,
    passingScore: 70,
    active: true,
    questions: [
      {
        id: "q-dom-1",
        assessmentId: "assess-dom-events",
        skillId: "javascript",
        question: "What are the three phases of DOM event propagation in order?",
        options: [
          "Capture phase, Target phase, Bubbling phase",
          "Bubbling phase, Target phase, Capture phase",
          "Trigger phase, Action phase, Complete phase",
          "Dispatch phase, Filter phase, Execute phase"
        ],
        correctAnswer: "Capture phase, Target phase, Bubbling phase",
        explanation: "Events travel down from the window to the target (Capture), fire on the target, and bubble back up the tree (Bubbling).",
        difficulty: "medium",
        points: 10,
        active: true,
      },
      {
        id: "q-dom-2",
        assessmentId: "assess-dom-events",
        skillId: "javascript",
        question: "What is the primary advantage of the Event Delegation pattern?",
        options: [
          "It executes events on a web worker thread",
          "It attaches a single listener on a parent element to handle events for all existing and future child elements",
          "It disables browser security checks",
          "It forces synchronous execution"
        ],
        correctAnswer: "It attaches a single listener on a parent element to handle events for all existing and future child elements",
        explanation: "Event delegation leverages event bubbling to handle dynamic child elements with lower memory overhead.",
        difficulty: "easy",
        points: 10,
        active: true,
      },
      {
        id: "q-dom-3",
        assessmentId: "assess-dom-events",
        skillId: "javascript",
        question: "Why should developers use 'textContent' instead of 'innerHTML' when inserting user-supplied text?",
        options: [
          "textContent is slower",
          "innerHTML parses strings as HTML, exposing the application to Cross-Site Scripting (XSS) if input contains malicious tags",
          "textContent only works on buttons",
          "innerHTML converts all text to uppercase"
        ],
        correctAnswer: "innerHTML parses strings as HTML, exposing the application to Cross-Site Scripting (XSS) if input contains malicious tags",
        explanation: "textContent safely escapes markup characters, treating the input strictly as plain text.",
        difficulty: "easy",
        points: 10,
        active: true,
      },
      {
        id: "q-dom-4",
        assessmentId: "assess-dom-events",
        skillId: "javascript",
        question: "What does 'event.preventDefault()' do when triggered on a form submit event?",
        options: [
          "It clears all input fields",
          "It halts browser default behavior (such as reloading the page or submitting via GET/POST)",
          "It stops event bubbling to parent nodes",
          "It closes the browser window"
        ],
        correctAnswer: "It halts browser default behavior (such as reloading the page or submitting via GET/POST)",
        explanation: "preventDefault() cancels the default action that belongs to the event.",
        difficulty: "easy",
        points: 10,
        active: true,
      },
      {
        id: "q-dom-5",
        assessmentId: "assess-dom-events",
        skillId: "javascript",
        question: "What is the difference between 'event.stopPropagation()' and 'event.preventDefault()'?",
        options: [
          "stopPropagation halts event bubbling up the DOM hierarchy; preventDefault cancels the browser's default action",
          "They are interchangeable synonyms",
          "stopPropagation resets the form",
          "preventDefault stops the event loop"
        ],
        correctAnswer: "stopPropagation halts event bubbling up the DOM hierarchy; preventDefault cancels the browser's default action",
        explanation: "stopPropagation controls event propagation flow; preventDefault controls native default browser behaviors.",
        difficulty: "medium",
        points: 10,
        active: true,
      },
      {
        id: "q-dom-6",
        assessmentId: "assess-dom-events",
        skillId: "javascript",
        question: "What does the Element.closest() method do?",
        options: [
          "Finds the closest child element with a tag",
          "Traverses the element and its parents (heading toward the document root) until it finds a node that matches the provided CSS selector",
          "Calculates pixel distance between two elements",
          "Returns the nearest sibling element"
        ],
        correctAnswer: "Traverses the element and its parents (heading toward the document root) until it finds a node that matches the provided CSS selector",
        explanation: "closest() searches upwards through ancestors for a matching selector, essential for event delegation.",
        difficulty: "medium",
        points: 10,
        active: true,
      },
      {
        id: "q-dom-7",
        assessmentId: "assess-dom-events",
        skillId: "javascript",
        question: "What is a major performance drawback of repeatedly querying the DOM and reading layout properties like 'offsetWidth' inside a tight loop?",
        options: [
          "It causes browser memory leaks",
          "It forces synchronous layout recalculations (layout thrashing / reflow), hurting frame rate",
          "It corrupts JavaScript scope",
          "It disconnects web sockets"
        ],
        correctAnswer: "It forces synchronous layout recalculations (layout thrashing / reflow), hurting frame rate",
        explanation: "Interleaving DOM writes and reads forces the browser to synchronously recompute styles and geometry repeatedly.",
        difficulty: "hard",
        points: 10,
        active: true,
      },
    ],
  },

  // ── 5. Web APIs / Fetch ───────────────────────────────────────────────────
  {
    id: "assess-web-apis-fetch",
    skillId: "javascript",
    title: "Asynchronous JavaScript & Fetch API Assessment",
    description: "Assess understanding of the Event Loop, Promises, async/await, and network error handling with Fetch.",
    difficulty: "Mixed",
    totalQuestions: 7,
    passingScore: 70,
    active: true,
    questions: [
      {
        id: "q-fetch-1",
        assessmentId: "assess-web-apis-fetch",
        skillId: "javascript",
        question: "Does the native fetch() Promise reject when the server responds with an HTTP 404 or 500 error code?",
        options: [
          "Yes, all non-200 responses automatically reject the fetch Promise",
          "No, fetch() only rejects on network failures or when the request is aborted; 404/500 resolve normally with response.ok set to false",
          "It depends on the browser version",
          "Yes, but only in production mode"
        ],
        correctAnswer: "No, fetch() only rejects on network failures or when the request is aborted; 404/500 resolve normally with response.ok set to false",
        explanation: "fetch() resolves successfully on any received HTTP response. Developers must explicitly check if (!response.ok).",
        difficulty: "medium",
        points: 10,
        active: true,
      },
      {
        id: "q-fetch-2",
        assessmentId: "assess-web-apis-fetch",
        skillId: "javascript",
        question: "What is the difference between microtasks (Promises, queueMicrotask) and macrotasks (setTimeout, setInterval) in the JavaScript Event Loop?",
        options: [
          "Microtasks run on the server, macrotasks run in the browser",
          "The microtask queue is exhausted completely after each task and before the next macrotask is processed",
          "Macrotasks execute before microtasks always",
          "There is no difference in execution priority"
        ],
        correctAnswer: "The microtask queue is exhausted completely after each task and before the next macrotask is processed",
        explanation: "Microtasks have higher priority and will run immediately when the call stack clears before the next macrotask tick.",
        difficulty: "hard",
        points: 10,
        active: true,
      },
      {
        id: "q-fetch-3",
        assessmentId: "assess-web-apis-fetch",
        skillId: "javascript",
        question: "What does 'Promise.all([p1, p2, p3])' do if one of the promises rejects?",
        options: [
          "It waits for all others to finish, then returns the successful values",
          "It rejects immediately with the error of the first rejected promise (fail-fast)",
          "It retries the failed promise up to 3 times",
          "It returns null"
        ],
        correctAnswer: "It rejects immediately with the error of the first rejected promise (fail-fast)",
        explanation: "Promise.all has fail-fast behavior: if any promise rejects, the entire returned promise rejects immediately.",
        difficulty: "medium",
        points: 10,
        active: true,
      },
      {
        id: "q-fetch-4",
        assessmentId: "assess-web-apis-fetch",
        skillId: "javascript",
        question: "Which API method enables graceful cancellation of an ongoing fetch() HTTP request?",
        options: ["fetch.abort()", "AbortController and its signal property", "window.cancelFetch()", "Promise.cancel()"],
        correctAnswer: "AbortController and its signal property",
        explanation: "Passing an AbortSignal from an AbortController allows developers to abort fetch requests when needed.",
        difficulty: "medium",
        points: 10,
        active: true,
      },
      {
        id: "q-fetch-5",
        assessmentId: "assess-web-apis-fetch",
        skillId: "javascript",
        question: "Why must you 'await response.json()' after awaiting 'fetch()'?",
        options: [
          "response.json() is an asynchronous stream reader that parses the readable body stream into a JavaScript object",
          "It is a required formality with no actual asynchronous work",
          "It converts headers into JSON",
          "It verifies the status code"
        ],
        correctAnswer: "response.json() is an asynchronous stream reader that parses the readable body stream into a JavaScript object",
        explanation: "The response body is an incoming stream; response.json() reads the full stream to completion asynchronously.",
        difficulty: "easy",
        points: 10,
        active: true,
      },
      {
        id: "q-fetch-6",
        assessmentId: "assess-web-apis-fetch",
        skillId: "javascript",
        question: "What does Promise.allSettled() return compared to Promise.all()?",
        options: [
          "An array of objects describing the outcome (fulfilled or rejected) of each promise, without early termination",
          "Only the rejected promises",
          "A single boolean value",
          "A synchronous callback"
        ],
        correctAnswer: "An array of objects describing the outcome (fulfilled or rejected) of each promise, without early termination",
        explanation: "Promise.allSettled() always waits for all input promises to either fulfill or reject.",
        difficulty: "medium",
        points: 10,
        active: true,
      },
      {
        id: "q-fetch-7",
        assessmentId: "assess-web-apis-fetch",
        skillId: "javascript",
        question: "What happens if an asynchronous function throws an unhandled error inside its body?",
        options: [
          "The entire Node.js/browser process freezes",
          "The function returns a rejected Promise wrapping the thrown error",
          "The error is silently ignored",
          "It automatically prints to the DOM"
        ],
        correctAnswer: "The function returns a rejected Promise wrapping the thrown error",
        explanation: "In async functions, uncaught exceptions are automatically transformed into Promise rejections.",
        difficulty: "easy",
        points: 10,
        active: true,
      },
    ],
  },

  // ── 6. Git and GitHub Fundamentals ────────────────────────────────────────
  {
    id: "assess-git-fundamentals",
    skillId: "git-github",
    title: "Git Version Control & Collaboration Assessment",
    description: "Verify knowledge of commit graphs, branching, merge conflicts, staging, and pull requests.",
    difficulty: "Mixed",
    totalQuestions: 7,
    passingScore: 70,
    active: true,
    questions: [
      {
        id: "q-git-1",
        assessmentId: "assess-git-fundamentals",
        skillId: "git-github",
        question: "What is the primary role of the Git staging area (Index)?",
        options: [
          "It stores remote backups of the repository",
          "It serves as a preparation buffer allowing developers to craft precise, selective commits before saving snapshots",
          "It resolves merge conflicts automatically",
          "It compiles code before running"
        ],
        correctAnswer: "It serves as a preparation buffer allowing developers to craft precise, selective commits before saving snapshots",
        explanation: "The staging area allows you to stage specific changed files or hunks (git add) to include in the next commit.",
        difficulty: "easy",
        points: 10,
        active: true,
      },
      {
        id: "q-git-2",
        assessmentId: "assess-git-fundamentals",
        skillId: "git-github",
        question: "What is the difference between 'git pull' and 'git fetch'?",
        options: [
          "git fetch downloads commits from remote without merging; git pull fetches and automatically merges into the current branch",
          "git fetch deletes remote branches; git pull creates them",
          "They are identical commands",
          "git pull cannot be used on main"
        ],
        correctAnswer: "git fetch downloads commits from remote without merging; git pull fetches and automatically merges into the current branch",
        explanation: "git pull is essentially shorthand for 'git fetch' followed by 'git merge' of the upstream tracking branch.",
        difficulty: "medium",
        points: 10,
        active: true,
      },
      {
        id: "q-git-3",
        assessmentId: "assess-git-fundamentals",
        skillId: "git-github",
        question: "What causes a Git merge conflict?",
        options: [
          "When two developers work on different repositories",
          "When two branches modify the same line of code in conflicting ways and Git cannot determine which version to keep",
          "When a commit message is longer than 50 characters",
          "When the remote server runs out of disk space"
        ],
        correctAnswer: "When two branches modify the same line of code in conflicting ways and Git cannot determine which version to keep",
        explanation: "Git automatically merges non-overlapping changes, but halts and requests human intervention when identical lines diverge.",
        difficulty: "easy",
        points: 10,
        active: true,
      },
      {
        id: "q-git-4",
        assessmentId: "assess-git-fundamentals",
        skillId: "git-github",
        question: "Why should API keys and secret service account credentials never be committed to a Git repository?",
        options: [
          "Git will reject commits containing secrets",
          "Once pushed, commits are permanently embedded in repository history and cloned across team machines, risking credential compromise",
          "Secrets slow down git checkout speed",
          "Git encrypts the file so it cannot be read"
        ],
        correctAnswer: "Once pushed, commits are permanently embedded in repository history and cloned across team machines, risking credential compromise",
        explanation: "Git history is immutable; committed secrets persist in git history even if deleted in a subsequent commit.",
        difficulty: "easy",
        points: 10,
        active: true,
      },
      {
        id: "q-git-5",
        assessmentId: "assess-git-fundamentals",
        skillId: "git-github",
        question: "What does 'git checkout -b feature/auth' do?",
        options: [
          "Deletes the branch feature/auth",
          "Creates a new branch named 'feature/auth' and switches your working directory to it",
          "Merges feature/auth into main",
          "Clones a repository"
        ],
        correctAnswer: "Creates a new branch named 'feature/auth' and switches your working directory to it",
        explanation: "The -b flag instructs checkout to create the branch first before switching to it.",
        difficulty: "easy",
        points: 10,
        active: true,
      },
      {
        id: "q-git-6",
        assessmentId: "assess-git-fundamentals",
        skillId: "git-github",
        question: "What does a fast-forward merge mean in Git?",
        options: [
          "A merge that skips commit verification",
          "The target branch has not diverged from the source branch, so Git simply advances the target branch pointer forward to the latest commit",
          "A merge resolved by GitHub Actions",
          "A squash merge"
        ],
        correctAnswer: "The target branch has not diverged from the source branch, so Git simply advances the target branch pointer forward to the latest commit",
        explanation: "Fast-forward merges occur when there are no divergent commits on the destination branch.",
        difficulty: "medium",
        points: 10,
        active: true,
      },
      {
        id: "q-git-7",
        assessmentId: "assess-git-fundamentals",
        skillId: "git-github",
        question: "What is the purpose of a Pull Request (PR) on GitHub?",
        options: [
          "To request permission to download Git",
          "To propose code changes from a branch, facilitate code review, run CI tests, and discuss modifications before merging into main",
          "To delete old branches automatically",
          "To compile TypeScript to JavaScript"
        ],
        correctAnswer: "To propose code changes from a branch, facilitate code review, run CI tests, and discuss modifications before merging into main",
        explanation: "PRs are the central collaborative mechanism for peer review, discussion, and automated checks.",
        difficulty: "easy",
        points: 10,
        active: true,
      },
    ],
  },

  // ── 7. React Fundamentals ─────────────────────────────────────────────────
  {
    id: "assess-react-fundamentals",
    skillId: "react",
    title: "React Fundamentals: Components, State & Hooks Assessment",
    description: "Measure mastery of component architecture, state management, hooks lifecycle, and reconciliation.",
    difficulty: "Mixed",
    totalQuestions: 7,
    passingScore: 70,
    active: true,
    questions: [
      {
        id: "q-react-1",
        assessmentId: "assess-react-fundamentals",
        skillId: "react",
        question: "Why should React state never be mutated directly (e.g. 'state.count = 5')?",
        options: [
          "JavaScript will throw a syntax error",
          "Direct mutations bypass React's reactive scheduling and will not trigger a component re-render",
          "It deletes the state variable permanently",
          "React only supports immutable primitive types"
        ],
        correctAnswer: "Direct mutations bypass React's reactive scheduling and will not trigger a component re-render",
        explanation: "React relies on referential equality and setter invocations to detect changes and trigger virtual DOM reconciliation.",
        difficulty: "easy",
        points: 10,
        active: true,
      },
      {
        id: "q-react-2",
        assessmentId: "assess-react-fundamentals",
        skillId: "react",
        question: "What is the significance of the 'key' prop when rendering lists in React?",
        options: [
          "It styles the list item as unique",
          "It helps React's reconciliation engine uniquely identify which items changed, were added, or were removed across renders",
          "It encrypts the list item data",
          "It provides the index of the element"
        ],
        correctAnswer: "It helps React's reconciliation engine uniquely identify which items changed, were added, or were removed across renders",
        explanation: "Stable unique keys enable React to preserve state and efficiently re-order DOM nodes without rebuilding the entire list.",
        difficulty: "easy",
        points: 10,
        active: true,
      },
      {
        id: "q-react-3",
        assessmentId: "assess-react-fundamentals",
        skillId: "react",
        question: "When does the callback inside 'useEffect(fn, [])' (empty dependency array) execute?",
        options: [
          "On every single component re-render",
          "Only once, immediately after the component mounts initially",
          "Before the component renders JSX",
          "Never"
        ],
        correctAnswer: "Only once, immediately after the component mounts initially",
        explanation: "An empty dependency array indicates the effect depends on no state or props, so it runs once upon initial mount.",
        difficulty: "easy",
        points: 10,
        active: true,
      },
      {
        id: "q-react-4",
        assessmentId: "assess-react-fundamentals",
        skillId: "react",
        question: "What is a 'stale closure' bug in a React useEffect hook?",
        options: [
          "When a hook is called conditionally",
          "When an effect references a state variable that was omitted from the dependency array, capturing an outdated value from a previous render",
          "When CSS styles fail to load",
          "When state is reset to undefined"
        ],
        correctAnswer: "When an effect references a state variable that was omitted from the dependency array, capturing an outdated value from a previous render",
        explanation: "If dependencies are omitted, the effect's closed-over scope continues referencing the variables from the initial render.",
        difficulty: "hard",
        points: 10,
        active: true,
      },
      {
        id: "q-react-5",
        assessmentId: "assess-react-fundamentals",
        skillId: "react",
        question: "What does the cleanup function returned from a useEffect hook accomplish?",
        options: [
          "It resets all component state to zero",
          "It runs before the effect re-runs or when the component unmounts to cancel timers, network subscriptions, or listeners",
          "It deletes the component from git",
          "It forces garbage collection"
        ],
        correctAnswer: "It runs before the effect re-runs or when the component unmounts to cancel timers, network subscriptions, or listeners",
        explanation: "Effect cleanup functions prevent memory leaks by dismantling active subscriptions when components unmount or deps change.",
        difficulty: "medium",
        points: 10,
        active: true,
      },
      {
        id: "q-react-6",
        assessmentId: "assess-react-fundamentals",
        skillId: "react",
        question: "Why can't React hooks be called inside loops, conditions, or nested functions?",
        options: [
          "JavaScript syntax forbids functions inside loops",
          "React relies on the exact invocation order of hooks across render passes to maintain internal state tracking",
          "It causes infinite loops automatically",
          "Hooks require strict compilation"
        ],
        correctAnswer: "React relies on the exact invocation order of hooks across render passes to maintain internal state tracking",
        explanation: "React maintains an internal linked list of hooks per component, requiring identical order on every render.",
        difficulty: "medium",
        points: 10,
        active: true,
      },
      {
        id: "q-react-7",
        assessmentId: "assess-react-fundamentals",
        skillId: "react",
        question: "What is 'prop drilling' and how can it be mitigated in complex React apps?",
        options: [
          "Running tests on props; mitigated with Jest",
          "Passing props down multiple intermediary component layers; mitigated with React Context, composition, or state management stores",
          "Deleting props; mitigated with const",
          "Validating prop types"
        ],
        correctAnswer: "Passing props down multiple intermediary component layers; mitigated with React Context, composition, or state management stores",
        explanation: "Prop drilling occurs when intermediate components must receive and forward props they do not use themselves.",
        difficulty: "medium",
        points: 10,
        active: true,
      },
    ],
  },

  // ── 8. Programming Fundamentals ───────────────────────────────────────────
  {
    id: "assess-programming-fundamentals",
    skillId: "javascript",
    title: "Programming Fundamentals & Data Structures Assessment",
    description: "Evaluate algorithmic thinking, complexity analysis (Big-O), search algorithms, and data structures.",
    difficulty: "Mixed",
    totalQuestions: 7,
    passingScore: 70,
    active: true,
    questions: [
      {
        id: "q-prog-1",
        assessmentId: "assess-programming-fundamentals",
        skillId: "javascript",
        question: "What is the average time complexity of searching for an element in a Hash Table (Map)?",
        options: ["O(n)", "O(log n)", "O(1)", "O(n^2)"],
        correctAnswer: "O(1)",
        explanation: "Direct hash addressing provides constant time O(1) average lookup performance.",
        difficulty: "easy",
        points: 10,
        active: true,
      },
      {
        id: "q-prog-2",
        assessmentId: "assess-programming-fundamentals",
        skillId: "javascript",
        question: "What is the time complexity of Binary Search on a pre-sorted array of n elements?",
        options: ["O(1)", "O(log n)", "O(n)", "O(n log n)"],
        correctAnswer: "O(log n)",
        explanation: "Binary search halves the remaining search space with each comparison step, yielding logarithmic O(log n) time.",
        difficulty: "easy",
        points: 10,
        active: true,
      },
      {
        id: "q-prog-3",
        assessmentId: "assess-programming-fundamentals",
        skillId: "javascript",
        question: "Which data structure operates on a Last-In, First-Out (LIFO) principle?",
        options: ["Queue", "Stack", "Binary Search Tree", "Linked List"],
        correctAnswer: "Stack",
        explanation: "A Stack pushes elements on top and pops elements from the top (LIFO).",
        difficulty: "easy",
        points: 10,
        active: true,
      },
      {
        id: "q-prog-4",
        assessmentId: "assess-programming-fundamentals",
        skillId: "javascript",
        question: "What happens if a recursive function is called without a base case?",
        options: [
          "It returns null",
          "It triggers a Maximum Call Stack Size Exceeded (Stack Overflow) error",
          "It automatically exits after 100 iterations",
          "The computer restarts"
        ],
        correctAnswer: "It triggers a Maximum Call Stack Size Exceeded (Stack Overflow) error",
        explanation: "Each recursive call consumes a call stack frame; without a terminating base case, the memory allocated for the stack is exhausted.",
        difficulty: "medium",
        points: 10,
        active: true,
      },
      {
        id: "q-prog-5",
        assessmentId: "assess-programming-fundamentals",
        skillId: "javascript",
        question: "Why is a Queue (FIFO) well-suited for Breadth-First Search (BFS) graph traversal?",
        options: [
          "It explores nodes in increasing order of their distance from the root by processing neighbors layer by layer",
          "It uses less memory than a stack in all cases",
          "It automatically sorts elements",
          "It avoids cycles without extra tracking"
        ],
        correctAnswer: "It explores nodes in increasing order of their distance from the root by processing neighbors layer by layer",
        explanation: "BFS explores all immediate neighbor nodes at the current depth before moving to nodes at the next depth level.",
        difficulty: "medium",
        points: 10,
        active: true,
      },
      {
        id: "q-prog-6",
        assessmentId: "assess-programming-fundamentals",
        skillId: "javascript",
        question: "What is the worst-case time complexity of standard QuickSort when the pivot selection is poor?",
        options: ["O(n log n)", "O(n^2)", "O(n)", "O(1)"],
        correctAnswer: "O(n^2)",
        explanation: "When partitions are unbalanced (e.g. sorted array with first element as pivot), QuickSort degrades to O(n^2).",
        difficulty: "hard",
        points: 10,
        active: true,
      },
      {
        id: "q-prog-7",
        assessmentId: "assess-programming-fundamentals",
        skillId: "javascript",
        question: "What does the Two-Pointer technique achieve when searching for pairs summing to target in a sorted array?",
        options: [
          "Reduces time complexity from O(n^2) nested loops down to O(n) linear scan",
          "Requires extra O(n) memory",
          "Calculates square root in O(1)",
          "Reverses the array"
        ],
        correctAnswer: "Reduces time complexity from O(n^2) nested loops down to O(n) linear scan",
        explanation: "Starting pointers at opposite ends and moving them based on sum comparisons achieves linear O(n) time.",
        difficulty: "medium",
        points: 10,
        active: true,
      },
    ],
  },

  // ── 9. HTTP Fundamentals ──────────────────────────────────────────────────
  {
    id: "assess-http-fundamentals",
    skillId: "computer-networks",
    title: "HTTP Protocol & Web Networking Assessment",
    description: "Measure understanding of HTTP request-response flow, status codes, headers, and web security.",
    difficulty: "Mixed",
    totalQuestions: 7,
    passingScore: 70,
    active: true,
    questions: [
      {
        id: "q-net-1",
        assessmentId: "assess-http-fundamentals",
        skillId: "computer-networks",
        question: "What is the difference between HTTP 401 Unauthorized and HTTP 403 Forbidden?",
        options: [
          "401 means authentication is missing or invalid; 403 means the user is authenticated but does not have permission for the resource",
          "401 is for servers; 403 is for browsers",
          "There is no difference",
          "401 is a success status code"
        ],
        correctAnswer: "401 means authentication is missing or invalid; 403 means the user is authenticated but does not have permission for the resource",
        explanation: "401 represents an authentication failure; 403 represents an authorization (permission) failure.",
        difficulty: "easy",
        points: 10,
        active: true,
      },
      {
        id: "q-net-2",
        assessmentId: "assess-http-fundamentals",
        skillId: "computer-networks",
        question: "Which HTTP status code should be returned after successfully creating a new resource via a POST request?",
        options: ["200 OK", "201 Created", "204 No Content", "301 Moved Permanently"],
        correctAnswer: "201 Created",
        explanation: "201 Created explicitly confirms the creation of a new entity, typically returning its location or representation.",
        difficulty: "easy",
        points: 10,
        active: true,
      },
      {
        id: "q-net-3",
        assessmentId: "assess-http-fundamentals",
        skillId: "computer-networks",
        question: "What is the primary purpose of the 'HttpOnly' flag on a session cookie?",
        options: [
          "It forces the cookie to only travel over HTTPS",
          "It prevents client-side JavaScript (e.g. document.cookie) from accessing the cookie, mitigating XSS token theft",
          "It deletes the cookie when the browser closes",
          "It translates the cookie to JSON"
        ],
        correctAnswer: "It prevents client-side JavaScript (e.g. document.cookie) from accessing the cookie, mitigating XSS token theft",
        explanation: "HttpOnly cookies cannot be read by JavaScript, blocking attackers from extracting session tokens via XSS.",
        difficulty: "medium",
        points: 10,
        active: true,
      },
      {
        id: "q-net-4",
        assessmentId: "assess-http-fundamentals",
        skillId: "computer-networks",
        question: "What triggers a browser to send a CORS preflight (OPTIONS) request before an actual API call?",
        options: [
          "Any GET request to the same origin",
          "Non-simple cross-origin requests, such as those using methods other than GET/POST or custom headers (e.g. Authorization, Content-Type: application/json)",
          "Image downloads",
          "WebSocket connections"
        ],
        correctAnswer: "Non-simple cross-origin requests, such as those using methods other than GET/POST or custom headers (e.g. Authorization, Content-Type: application/json)",
        explanation: "Browsers send preflight OPTIONS requests to check if the cross-origin server permits the requested method and headers.",
        difficulty: "medium",
        points: 10,
        active: true,
      },
      {
        id: "q-net-5",
        assessmentId: "assess-http-fundamentals",
        skillId: "computer-networks",
        question: "What does the 'Strict-Transport-Security' (HSTS) header instruct the browser to do?",
        options: [
          "Enforce strict password requirements",
          "Automatically convert all subsequent insecure HTTP connections to the domain into HTTPS before transmitting packets",
          "Block all cookies",
          "Disable cache"
        ],
        correctAnswer: "Automatically convert all subsequent insecure HTTP connections to the domain into HTTPS before transmitting packets",
        explanation: "HSTS protects against man-in-the-middle SSL-stripping attacks by mandating HTTPS client-side.",
        difficulty: "medium",
        points: 10,
        active: true,
      },
      {
        id: "q-net-6",
        assessmentId: "assess-http-fundamentals",
        skillId: "computer-networks",
        question: "Which HTTP method is designed for partial updates to an existing resource?",
        options: ["PUT", "PATCH", "POST", "UPDATE"],
        correctAnswer: "PATCH",
        explanation: "PATCH is explicitly standardized for partial resource modifications, while PUT represents full replacement.",
        difficulty: "easy",
        points: 10,
        active: true,
      },
      {
        id: "q-net-7",
        assessmentId: "assess-http-fundamentals",
        skillId: "computer-networks",
        question: "What is an HTTP 503 status code indicating?",
        options: [
          "The resource was deleted",
          "The server is temporarily unable to handle the request due to maintenance, overload, or missing configuration",
          "The client entered an invalid password",
          "The request succeeded with no body"
        ],
        correctAnswer: "The server is temporarily unable to handle the request due to maintenance, overload, or missing configuration",
        explanation: "503 Service Unavailable signals temporary downtime or misconfiguration rather than a permanent failure.",
        difficulty: "easy",
        points: 10,
        active: true,
      },
    ],
  },

  // ── 10. REST API Concepts ─────────────────────────────────────────────────
  {
    id: "assess-rest-api-concepts",
    skillId: "rest-apis",
    title: "REST Architecture & Resource Design Assessment",
    description: "Evaluate resource naming, idempotency, HTTP verb semantics, and REST contract design.",
    difficulty: "Mixed",
    totalQuestions: 7,
    passingScore: 70,
    active: true,
    questions: [
      {
        id: "q-rest-1",
        assessmentId: "assess-rest-api-concepts",
        skillId: "rest-apis",
        question: "Which URI conforms best to RESTful resource modeling conventions?",
        options: [
          "/api/getAllStudents",
          "/api/v1/students",
          "/api/student/create_new",
          "/api/doDeleteStudent?id=5"
        ],
        correctAnswer: "/api/v1/students",
        explanation: "RESTful URIs use plural nouns to identify resource collections, using HTTP verbs to indicate the desired operation.",
        difficulty: "easy",
        points: 10,
        active: true,
      },
      {
        id: "q-rest-2",
        assessmentId: "assess-rest-api-concepts",
        skillId: "rest-apis",
        question: "What does idempotency mean in the context of REST APIs?",
        options: [
          "The endpoint responds in under 50 milliseconds",
          "Making the same request multiple times produces the exact same server state as making it a single time",
          "The endpoint does not require authentication",
          "The endpoint is cached by the browser"
        ],
        correctAnswer: "Making the same request multiple times produces the exact same server state as making it a single time",
        explanation: "An operation is idempotent if its side effects on server state are identical whether executed once or repeatedly.",
        difficulty: "medium",
        points: 10,
        active: true,
      },
      {
        id: "q-rest-3",
        assessmentId: "assess-rest-api-concepts",
        skillId: "rest-apis",
        question: "Which of the following HTTP methods are idempotent in REST?",
        options: [
          "POST and PATCH",
          "GET, PUT, and DELETE",
          "POST only",
          "None of them"
        ],
        correctAnswer: "GET, PUT, and DELETE",
        explanation: "GET (reads), PUT (replaces with exact state), and DELETE (removes resource) produce identical state when repeated.",
        difficulty: "medium",
        points: 10,
        active: true,
      },
      {
        id: "q-rest-4",
        assessmentId: "assess-rest-api-concepts",
        skillId: "rest-apis",
        question: "What is the recommended status code when a DELETE request successfully removes a resource and returns no body content?",
        options: ["200 OK", "204 No Content", "202 Accepted", "404 Not Found"],
        correctAnswer: "204 No Content",
        explanation: "204 No Content confirms that the action succeeded and the response payload is intentionally empty.",
        difficulty: "easy",
        points: 10,
        active: true,
      },
      {
        id: "q-rest-5",
        assessmentId: "assess-rest-api-concepts",
        skillId: "rest-apis",
        question: "How should sub-resources be represented in a RESTful hierarchy (e.g. assessments belonging to a specific student)?",
        options: [
          "/api/v1/students/:studentId/assessments",
          "/api/v1/getAssessmentsByStudentId?id=:studentId",
          "/api/v1/student_assessments_table",
          "/api/v1/allData"
        ],
        correctAnswer: "/api/v1/students/:studentId/assessments",
        explanation: "Nested resource paths naturally express parent-child relationships in REST.",
        difficulty: "easy",
        points: 10,
        active: true,
      },
      {
        id: "q-rest-6",
        assessmentId: "assess-rest-api-concepts",
        skillId: "rest-apis",
        question: "Why should REST endpoints that return collections always implement pagination?",
        options: [
          "Browsers crash if JSON has more than 10 lines",
          "Unbounded collection queries can overwhelm database memory, increase network payload latency, and cause denial of service",
          "REST requires all arrays to have length <= 20",
          "It encrypts the payload"
        ],
        correctAnswer: "Unbounded collection queries can overwhelm database memory, increase network payload latency, and cause denial of service",
        explanation: "Pagination ensures predictable, bounded memory utilization and network response times.",
        difficulty: "easy",
        points: 10,
        active: true,
      },
      {
        id: "q-rest-7",
        assessmentId: "assess-rest-api-concepts",
        skillId: "rest-apis",
        question: "What is the purpose of the 'Location' header in a 201 Created response?",
        options: [
          "It specifies the geographic server datacenter",
          "It provides the canonical URI of the newly created resource so the client knows where to access it",
          "It redirects the browser to login",
          "It specifies client IP"
        ],
        correctAnswer: "It provides the canonical URI of the newly created resource so the client knows where to access it",
        explanation: "The Location header points directly to the newly allocated resource URL.",
        difficulty: "medium",
        points: 10,
        active: true,
      },
    ],
  },

  // ── 11. Node.js Fundamentals ──────────────────────────────────────────────
  {
    id: "assess-nodejs-fundamentals",
    skillId: "nodejs",
    title: "Node.js Architecture & Runtime Assessment",
    description: "Assess understanding of non-blocking I/O, event loop mechanics, modules, and process management.",
    difficulty: "Mixed",
    totalQuestions: 7,
    passingScore: 70,
    active: true,
    questions: [
      {
        id: "q-node-1",
        assessmentId: "assess-nodejs-fundamentals",
        skillId: "nodejs",
        question: "Why does calling 'fs.readFileSync' inside an HTTP request handler harm Node.js performance?",
        options: [
          "It creates extra threads",
          "Because Node.js executes JavaScript on a single thread, synchronous file I/O blocks the entire event loop, freezing all concurrent user requests",
          "readFileSync is deprecated and throws errors",
          "It corrupts file content"
        ],
        correctAnswer: "Because Node.js executes JavaScript on a single thread, synchronous file I/O blocks the entire event loop, freezing all concurrent user requests",
        explanation: "Synchronous operations monopolize the single event loop thread, stopping all other concurrent operations.",
        difficulty: "easy",
        points: 10,
        active: true,
      },
      {
        id: "q-node-2",
        assessmentId: "assess-nodejs-fundamentals",
        skillId: "nodejs",
        question: "What underlying C library powers Node.js asynchronous I/O and the thread pool?",
        options: ["glibc", "libuv", "V8", "boost"],
        correctAnswer: "libuv",
        explanation: "libuv is the multi-platform C library providing the event loop, thread pool, and non-blocking I/O in Node.js.",
        difficulty: "medium",
        points: 10,
        active: true,
      },
      {
        id: "q-node-3",
        assessmentId: "assess-nodejs-fundamentals",
        skillId: "nodejs",
        question: "What is the difference between 'process.nextTick()' and 'setImmediate()'?",
        options: [
          "process.nextTick fires immediately after the current operation finishes (before any other microtasks/macrotasks); setImmediate fires on the next event loop check phase",
          "setImmediate runs first",
          "There is no difference",
          "process.nextTick is only available in Python"
        ],
        correctAnswer: "process.nextTick fires immediately after the current operation finishes (before any other microtasks/macrotasks); setImmediate fires on the next event loop check phase",
        explanation: "nextTick callbacks are prioritized before the event loop continues to subsequent phases.",
        difficulty: "hard",
        points: 10,
        active: true,
      },
      {
        id: "q-node-4",
        assessmentId: "assess-nodejs-fundamentals",
        skillId: "nodejs",
        question: "How do you securely supply configuration secrets (database URLs, API tokens) to a Node.js application in production?",
        options: [
          "Hardcode them in index.js and commit to git",
          "Inject them as Environment Variables (accessible via process.env) at deployment time",
          "Write them to public/secrets.txt",
          "Store them in the browser localStorage"
        ],
        correctAnswer: "Inject them as Environment Variables (accessible via process.env) at deployment time",
        explanation: "Environment variables keep sensitive infrastructure secrets decoupled from the codebase and out of version control.",
        difficulty: "easy",
        points: 10,
        active: true,
      },
      {
        id: "q-node-5",
        assessmentId: "assess-nodejs-fundamentals",
        skillId: "nodejs",
        question: "What is the purpose of Node.js Streams?",
        options: [
          "To format JSON data",
          "To process continuous streams of data chunk-by-chunk without reading the entire payload into RAM memory at once",
          "To run multithreaded computations",
          "To speed up CSS compilation"
        ],
        correctAnswer: "To process continuous streams of data chunk-by-chunk without reading the entire payload into RAM memory at once",
        explanation: "Streams enable memory-efficient handling of large files or network payloads by processing chunks incrementally.",
        difficulty: "medium",
        points: 10,
        active: true,
      },
      {
        id: "q-node-6",
        assessmentId: "assess-nodejs-fundamentals",
        skillId: "nodejs",
        question: "What does the 'npm ci' command do compared to 'npm install'?",
        options: [
          "It compiles C++ modules",
          "It performs a clean, deterministic install strictly matching package-lock.json without modifying or updating dependencies",
          "It deletes node_modules and builds the Next.js app",
          "It updates all packages to latest version"
        ],
        correctAnswer: "It performs a clean, deterministic install strictly matching package-lock.json without modifying or updating dependencies",
        explanation: "npm ci is built for CI/CD and production environments to ensure exact, reproducible dependency trees.",
        difficulty: "medium",
        points: 10,
        active: true,
      },
      {
        id: "q-node-7",
        assessmentId: "assess-nodejs-fundamentals",
        skillId: "nodejs",
        question: "What does 'ERR_REQUIRE_ESM' mean in Node.js runtime?",
        options: [
          "ESM modules cannot be imported",
          "CommonJS require() attempted to synchronously load an ECMAScript Module (ESM), which is strictly forbidden in Node",
          "The file path does not exist",
          "A TypeScript type error occurred"
        ],
        correctAnswer: "CommonJS require() attempted to synchronously load an ECMAScript Module (ESM), which is strictly forbidden in Node",
        explanation: "Because ESM modules may contain top-level await, synchronous CommonJS require() cannot load them directly.",
        difficulty: "hard",
        points: 10,
        active: true,
      },
    ],
  },

  // ── 12. Express.js ────────────────────────────────────────────────────────
  {
    id: "assess-express-fundamentals",
    skillId: "nodejs",
    title: "Express.js Architecture & Middleware Assessment",
    description: "Measure skills in middleware chaining, routing, centralized error handlers, and request pipeline.",
    difficulty: "Mixed",
    totalQuestions: 7,
    passingScore: 70,
    active: true,
    questions: [
      {
        id: "q-exp-1",
        assessmentId: "assess-express-fundamentals",
        skillId: "nodejs",
        question: "What happens if a custom Express middleware does not call 'next()' and does not send a response (res.send/res.json)?",
        options: [
          "Express calls next() automatically after 5 seconds",
          "The client request hangs indefinitely until the browser or server connection times out",
          "It returns HTTP 200",
          "Express throws a compilation error"
        ],
        correctAnswer: "The client request hangs indefinitely until the browser or server connection times out",
        explanation: "Middleware functions must either invoke next() to pass control or terminate the request by sending a response.",
        difficulty: "easy",
        points: 10,
        active: true,
      },
      {
        id: "q-exp-2",
        assessmentId: "assess-express-fundamentals",
        skillId: "nodejs",
        question: "How does Express recognize an Error-Handling middleware compared to a standard middleware?",
        options: [
          "By its name 'errorHandler'",
          "By having exactly four arguments: (err, req, res, next)",
          "By using the @catch decorator",
          "By returning a rejected Promise"
        ],
        correctAnswer: "By having exactly four arguments: (err, req, res, next)",
        explanation: "Express checks function.length === 4 to register a middleware specifically as an error handler.",
        difficulty: "medium",
        points: 10,
        active: true,
      },
      {
        id: "q-exp-3",
        assessmentId: "assess-express-fundamentals",
        skillId: "nodejs",
        question: "What is the purpose of 'app.use(express.json())'?",
        options: [
          "To send JSON responses to the client",
          "To parse incoming request bodies with Content-Type: application/json and expose the parsed object on req.body",
          "To format logs as JSON",
          "To validate JSON schemas"
        ],
        correctAnswer: "To parse incoming request bodies with Content-Type: application/json and expose the parsed object on req.body",
        explanation: "express.json() parses raw body streams into JavaScript objects on req.body.",
        difficulty: "easy",
        points: 10,
        active: true,
      },
      {
        id: "q-exp-4",
        assessmentId: "assess-express-fundamentals",
        skillId: "nodejs",
        question: "In the route '/api/students/:id', how do you access the value of 'id' inside the handler?",
        options: ["req.query.id", "req.params.id", "req.body.id", "req.headers.id"],
        correctAnswer: "req.params.id",
        explanation: "Route parameters defined with a colon are populated on the req.params object.",
        difficulty: "easy",
        points: 10,
        active: true,
      },
      {
        id: "q-exp-5",
        assessmentId: "assess-express-fundamentals",
        skillId: "nodejs",
        question: "What error is triggered if a handler executes 'res.json({ a: 1 })' and then later executes 'res.json({ b: 2 })' in the same request path?",
        options: [
          "SyntaxError",
          "Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client",
          "ReferenceError",
          "TypeError: res.json is not a function"
        ],
        correctAnswer: "Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client",
        explanation: "Once a response is dispatched, HTTP headers are closed and no additional response headers or body can be sent.",
        difficulty: "medium",
        points: 10,
        active: true,
      },
      {
        id: "q-exp-6",
        assessmentId: "assess-express-fundamentals",
        skillId: "nodejs",
        question: "Where in the middleware stack should Express centralized error-handling middleware be registered?",
        options: [
          "At the very beginning of the file before all routes",
          "At the very end of the middleware stack, after all application routes are mounted",
          "Inside each individual route controller",
          "In a separate worker thread"
        ],
        correctAnswer: "At the very end of the middleware stack, after all application routes are mounted",
        explanation: "Error handlers must be declared last so that errors forwarded via next(err) propagate down into them.",
        difficulty: "medium",
        points: 10,
        active: true,
      },
      {
        id: "q-exp-7",
        assessmentId: "assess-express-fundamentals",
        skillId: "nodejs",
        question: "What does 'express.Router()' provide?",
        options: [
          "Hardware network routing",
          "A modular, mountable mini-application and router system for organizing endpoint groups",
          "WebSocket connections",
          "Client-side navigation"
        ],
        correctAnswer: "A modular, mountable mini-application and router system for organizing endpoint groups",
        explanation: "Express Routers isolate route definitions into clean, modular files mounted under path prefixes.",
        difficulty: "easy",
        points: 10,
        active: true,
      },
    ],
  },

  // ── 13. Database Fundamentals ─────────────────────────────────────────────
  {
    id: "assess-database-fundamentals",
    skillId: "sql",
    title: "SQL & Relational Database Fundamentals Assessment",
    description: "Assess schema modeling, SQL joins, grouping, indexing, and ACID transaction concepts.",
    difficulty: "Mixed",
    totalQuestions: 7,
    passingScore: 70,
    active: true,
    questions: [
      {
        id: "q-sql-1",
        assessmentId: "assess-database-fundamentals",
        skillId: "sql",
        question: "What are the four ACID properties in database transaction management?",
        options: [
          "Action, Consistency, Index, Durability",
          "Atomicity, Consistency, Isolation, Durability",
          "Accuracy, Completeness, Integrity, Data",
          "Automatic, Compiled, Isolated, Decoupled"
        ],
        correctAnswer: "Atomicity, Consistency, Isolation, Durability",
        explanation: "ACID guarantees that transactions execute reliably: all-or-nothing (Atomicity), valid transitions (Consistency), concurrency isolation (Isolation), and persistence (Durability).",
        difficulty: "easy",
        points: 10,
        active: true,
      },
      {
        id: "q-sql-2",
        assessmentId: "assess-database-fundamentals",
        skillId: "sql",
        question: "What is the primary difference between an INNER JOIN and a LEFT JOIN?",
        options: [
          "INNER JOIN only returns rows with matching keys in both tables; LEFT JOIN returns all rows from the left table plus matching rows from the right table",
          "LEFT JOIN is faster",
          "INNER JOIN deletes non-matching rows permanently",
          "LEFT JOIN only works on strings"
        ],
        correctAnswer: "INNER JOIN only returns rows with matching keys in both tables; LEFT JOIN returns all rows from the left table plus matching rows from the right table",
        explanation: "LEFT JOIN preserves all records from the left side, filling non-matching right columns with NULL.",
        difficulty: "easy",
        points: 10,
        active: true,
      },
      {
        id: "q-sql-3",
        assessmentId: "assess-database-fundamentals",
        skillId: "sql",
        question: "When should the 'HAVING' clause be used instead of 'WHERE'?",
        options: [
          "HAVING is used to filter grouped rows based on aggregate function results (e.g. HAVING COUNT(*) > 5); WHERE filters individual rows before aggregation",
          "HAVING is used for primary keys",
          "They can be used interchangeably everywhere",
          "HAVING is only for text comparisons"
        ],
        correctAnswer: "HAVING is used to filter grouped rows based on aggregate function results (e.g. HAVING COUNT(*) > 5); WHERE filters individual rows before aggregation",
        explanation: "WHERE filters rows before GROUP BY aggregation; HAVING filters groups after aggregation.",
        difficulty: "medium",
        points: 10,
        active: true,
      },
      {
        id: "q-sql-4",
        assessmentId: "assess-database-fundamentals",
        skillId: "sql",
        question: "How do database indexes speed up SELECT query performance?",
        options: [
          "By deleting duplicate rows",
          "By maintaining a sorted balanced-tree (B-Tree) or hash data structure pointing directly to physical row storage locations",
          "By compressing the database into RAM",
          "By converting queries to C++"
        ],
        correctAnswer: "By maintaining a sorted balanced-tree (B-Tree) or hash data structure pointing directly to physical row storage locations",
        explanation: "B-Tree indexes allow O(log n) lookups instead of scanning every row in the table (O(n) full table scan).",
        difficulty: "medium",
        points: 10,
        active: true,
      },
      {
        id: "q-sql-5",
        assessmentId: "assess-database-fundamentals",
        skillId: "sql",
        question: "Why does parameterized querying protect against SQL Injection (SQLi)?",
        options: [
          "It encrypts the entire database",
          "It separates SQL code structure from untrusted user parameters, ensuring values are treated strictly as data literals rather than executable SQL commands",
          "It limits query length to 100 characters",
          "It automatically runs in read-only mode"
        ],
        correctAnswer: "It separates SQL code structure from untrusted user parameters, ensuring values are treated strictly as data literals rather than executable SQL commands",
        explanation: "Parameters are bound separately to the pre-compiled query plan, preventing malicious input from escaping into syntax.",
        difficulty: "medium",
        points: 10,
        active: true,
      },
      {
        id: "q-sql-6",
        assessmentId: "assess-database-fundamentals",
        skillId: "sql",
        question: "What is a Foreign Key constraint in a relational database?",
        options: [
          "A key connecting external third-party APIs",
          "A column that enforces referential integrity by ensuring its values must match an existing primary key in another table",
          "A temporary password for remote access",
          "A hidden column generated by the database"
        ],
        correctAnswer: "A column that enforces referential integrity by ensuring its values must match an existing primary key in another table",
        explanation: "Foreign keys prevent orphaned records and maintain valid relational associations across tables.",
        difficulty: "easy",
        points: 10,
        active: true,
      },
      {
        id: "q-sql-7",
        assessmentId: "assess-database-fundamentals",
        skillId: "sql",
        question: "What is a downside of having too many indexes on a database table?",
        options: [
          "The table cannot be read anymore",
          "Write operations (INSERT, UPDATE, DELETE) become slower because every index must be updated on every mutation, and index storage increases",
          "Queries fail if there are more than 3 indexes",
          "Foreign keys stop working"
        ],
        correctAnswer: "Write operations (INSERT, UPDATE, DELETE) become slower because every index must be updated on every mutation, and index storage increases",
        explanation: "Every write incurs write-amplification to maintain index data structures, requiring a balance between read and write speed.",
        difficulty: "hard",
        points: 10,
        active: true,
      },
    ],
  },

  // ── 14. Authentication Fundamentals ───────────────────────────────────────
  {
    id: "assess-auth-fundamentals",
    skillId: "auth-security",
    title: "Authentication & Web Security Assessment",
    description: "Evaluate understanding of secure password hashing, JWT architecture, session tokens, and access control.",
    difficulty: "Mixed",
    totalQuestions: 7,
    passingScore: 70,
    active: true,
    questions: [
      {
        id: "q-auth-1",
        assessmentId: "assess-auth-fundamentals",
        skillId: "auth-security",
        question: "Why are fast cryptographic hashing algorithms like MD5 or SHA-256 unsuitable for password storage?",
        options: [
          "They cannot hash strings longer than 10 characters",
          "Modern GPUs can compute billions of MD5/SHA-256 hashes per second, making offline dictionary and brute-force attacks trivial",
          "They are proprietary algorithms",
          "They produce random outputs"
        ],
        correctAnswer: "Modern GPUs can compute billions of MD5/SHA-256 hashes per second, making offline dictionary and brute-force attacks trivial",
        explanation: "Password hashing requires computationally slow, adaptive key-derivation functions (bcrypt, Argon2, scrypt).",
        difficulty: "medium",
        points: 10,
        active: true,
      },
      {
        id: "q-auth-2",
        assessmentId: "assess-auth-fundamentals",
        skillId: "auth-security",
        question: "What is the purpose of a unique cryptographic 'salt' in password hashing?",
        options: [
          "To make the password shorter",
          "To ensure identical passwords generate completely different hashes, neutralizing pre-computed Rainbow Table attacks",
          "To encrypt the password symmetrically",
          "To verify email addresses"
        ],
        correctAnswer: "To ensure identical passwords generate completely different hashes, neutralizing pre-computed Rainbow Table attacks",
        explanation: "A salt adds random data to the password before hashing so that identical passwords yield distinct hash strings.",
        difficulty: "easy",
        points: 10,
        active: true,
      },
      {
        id: "q-auth-3",
        assessmentId: "assess-auth-fundamentals",
        skillId: "auth-security",
        question: "What are the three dot-separated components of a JSON Web Token (JWT)?",
        options: [
          "Header, Payload, Signature",
          "Username, Password, Role",
          "Protocol, Domain, Path",
          "Cipher, Nonce, Key"
        ],
        correctAnswer: "Header, Payload, Signature",
        explanation: "A JWT consists of base64url-encoded Header and Payload, followed by a cryptographic Signature (header.payload.signature).",
        difficulty: "easy",
        points: 10,
        active: true,
      },
      {
        id: "q-auth-4",
        assessmentId: "assess-auth-fundamentals",
        skillId: "auth-security",
        question: "Can an attacker read the claims (data) stored inside the Payload of a standard signed JWT?",
        options: [
          "No, JWTs are automatically encrypted",
          "Yes, standard JWT payloads are only Base64URL-encoded, not encrypted; anyone with the token can inspect the payload claims",
          "Only if they have the private key",
          "Never"
        ],
        correctAnswer: "Yes, standard JWT payloads are only Base64URL-encoded, not encrypted; anyone with the token can inspect the payload claims",
        explanation: "JWT signatures ensure integrity (tamper-detection), not confidentiality. Never store plaintext secrets inside JWT payloads.",
        difficulty: "medium",
        points: 10,
        active: true,
      },
      {
        id: "q-auth-5",
        assessmentId: "assess-auth-fundamentals",
        skillId: "auth-security",
        question: "What is account enumeration and how does SkillBridge defend against it on the Forgot Password page?",
        options: [
          "Counting user scores; defended by hiding profiles",
          "An attacker testing emails to discover who has an account; defended by returning identical generic success confirmation regardless of whether the email exists",
          "Resetting all student passwords at once",
          "A rate limit algorithm"
        ],
        correctAnswer: "An attacker testing emails to discover who has an account; defended by returning identical generic success confirmation regardless of whether the email exists",
        explanation: "Returning consistent messages prevents attackers from verifying registered user email lists.",
        difficulty: "medium",
        points: 10,
        active: true,
      },
      {
        id: "q-auth-6",
        assessmentId: "assess-auth-fundamentals",
        skillId: "auth-security",
        question: "What is a major security risk of storing authentication tokens in browser 'localStorage'?",
        options: [
          "localStorage is limited to 5MB",
          "Any Cross-Site Scripting (XSS) vulnerability on the page can execute JavaScript to read and steal the token from localStorage",
          "localStorage deletes data on page refresh",
          "It only works on desktop browsers"
        ],
        correctAnswer: "Any Cross-Site Scripting (XSS) vulnerability on the page can execute JavaScript to read and steal the token from localStorage",
        explanation: "localStorage is accessible to any script running on the origin, making it vulnerable to XSS theft.",
        difficulty: "medium",
        points: 10,
        active: true,
      },
      {
        id: "q-auth-7",
        assessmentId: "assess-auth-fundamentals",
        skillId: "auth-security",
        question: "What is the purpose of timing-safe comparisons (crypto.timingSafeEqual) when verifying secrets or signatures?",
        options: [
          "To speed up execution",
          "To prevent Side-Channel Timing Attacks where attackers measure character-by-character comparison durations to deduce the secret",
          "To set token expiration time",
          "To format timestamps"
        ],
        correctAnswer: "To prevent Side-Channel Timing Attacks where attackers measure character-by-character comparison durations to deduce the secret",
        explanation: "Standard equality exits early on the first mismatched byte; timing-safe checks inspect all bytes in constant time.",
        difficulty: "hard",
        points: 10,
        active: true,
      },
    ],
  },

  // ── 15. API Development ───────────────────────────────────────────────────
  {
    id: "assess-api-development",
    skillId: "rest-apis",
    title: "Production API Architecture & Resiliency Assessment",
    description: "Assess API error sanitization, rate limiting, request validation, and production observability.",
    difficulty: "Mixed",
    totalQuestions: 7,
    passingScore: 70,
    active: true,
    questions: [
      {
        id: "q-api-1",
        assessmentId: "assess-api-development",
        skillId: "rest-apis",
        question: "Why must internal server error details (database queries, stack traces) be sanitized before responding to public API clients?",
        options: [
          "To reduce JSON payload size by 10 bytes",
          "Exposing internal file paths, query structures, or package versions aids attackers in reconnaissance and exploiting system vulnerabilities",
          "HTTP specifications forbid strings longer than 50 characters",
          "Browsers reject responses with stack traces"
        ],
        correctAnswer: "Exposing internal file paths, query structures, or package versions aids attackers in reconnaissance and exploiting system vulnerabilities",
        explanation: "Information disclosure vulnerabilities reveal internal architecture and exploit opportunities.",
        difficulty: "easy",
        points: 10,
        active: true,
      },
      {
        id: "q-api-2",
        assessmentId: "assess-api-development",
        skillId: "rest-apis",
        question: "What is the HTTP status code returned when a client exceeds their allocated API rate limit quota?",
        options: ["400 Bad Request", "403 Forbidden", "429 Too Many Requests", "503 Service Unavailable"],
        correctAnswer: "429 Too Many Requests",
        explanation: "RFC 6585 explicitly designates 429 Too Many Requests for rate limiting.",
        difficulty: "easy",
        points: 10,
        active: true,
      },
      {
        id: "q-api-3",
        assessmentId: "assess-api-development",
        skillId: "rest-apis",
        question: "What is an Idempotency Key header used for in payment or mission-critical API requests?",
        options: [
          "To encrypt the payment data",
          "To allow clients to safely retry a request without executing the underlying transaction twice if a network failure occurs",
          "To authenticate the user",
          "To bypass rate limits"
        ],
        correctAnswer: "To allow clients to safely retry a request without executing the underlying transaction twice if a network failure occurs",
        explanation: "The server stores processed keys and replays the cached result if the same key is received again.",
        difficulty: "medium",
        points: 10,
        active: true,
      },
      {
        id: "q-api-4",
        assessmentId: "assess-api-development",
        skillId: "rest-apis",
        question: "What should a production API health-check endpoint (/api/health) verify?",
        options: [
          "Only that the web server process is running, plus key dependencies like database and cache connectivity",
          "All student assessment scores",
          "Git branch history",
          "Frontend CSS styling"
        ],
        correctAnswer: "Only that the web server process is running, plus key dependencies like database and cache connectivity",
        explanation: "Liveness and readiness health checks verify vital service process health and critical downstream connectivity.",
        difficulty: "medium",
        points: 10,
        active: true,
      },
      {
        id: "q-api-5",
        assessmentId: "assess-api-development",
        skillId: "rest-apis",
        question: "Which request validation pattern is recommended in modern backend engineering?",
        options: [
          "Manual nested if/else statements spread across database queries",
          "Schema-based validation libraries (Zod, Joi) that validate and coerce request payloads at the route boundary before business logic runs",
          "Trusting all client input without validation",
          "Client-side validation only"
        ],
        correctAnswer: "Schema-based validation libraries (Zod, Joi) that validate and coerce request payloads at the route boundary before business logic runs",
        explanation: "Declarative boundary validation prevents malformed payloads from entering application layers.",
        difficulty: "easy",
        points: 10,
        active: true,
      },
      {
        id: "q-api-6",
        assessmentId: "assess-api-development",
        skillId: "rest-apis",
        question: "Why is API versioning (e.g. /api/v1/ vs /api/v2/) essential for production services?",
        options: [
          "It allows developers to introduce breaking contract changes without disrupting existing mobile or third-party client integrations",
          "It is required by the HTTP standard",
          "It makes queries run twice as fast",
          "It creates duplicate databases automatically"
        ],
        correctAnswer: "It allows developers to introduce breaking contract changes without disrupting existing mobile or third-party client integrations",
        explanation: "Versioning protects backwards compatibility when evolution requires non-additive changes.",
        difficulty: "easy",
        points: 10,
        active: true,
      },
      {
        id: "q-api-7",
        assessmentId: "assess-api-development",
        skillId: "rest-apis",
        question: "What is the purpose of a Correlation ID / Request ID header (e.g. X-Request-ID) in distributed systems?",
        options: [
          "To bill the user per request",
          "To trace a single request's lifecycle, logs, and errors across multiple microservices and database tiers",
          "To hash user passwords",
          "To compress responses"
        ],
        correctAnswer: "To trace a single request's lifecycle, logs, and errors across multiple microservices and database tiers",
        explanation: "A unique Request ID ties log statements across independent services together during debugging and incident response.",
        difficulty: "medium",
        points: 10,
        active: true,
      },
    ],
  },

  // ── 16. Full Stack Integration ────────────────────────────────────────────
  {
    id: "assess-fullstack-integration",
    skillId: "fullstack-integration",
    title: "Full Stack Integration & System Architecture Assessment",
    description: "Evaluate end-to-end integration across frontend interfaces, API layers, database state, and production workflows.",
    difficulty: "Mixed",
    totalQuestions: 7,
    passingScore: 70,
    active: true,
    questions: [
      {
        id: "q-fs-1",
        assessmentId: "assess-fullstack-integration",
        skillId: "fullstack-integration",
        question: "What is an 'Optimistic UI' update and when is it appropriate to use?",
        options: [
          "An update that assumes the network will always fail",
          "Immediately updating the client UI under the assumption that the server request will succeed, and rolling back if it fails",
          "An update that waits 10 seconds before rendering",
          "An automatic database migration"
        ],
        correctAnswer: "Immediately updating the client UI under the assumption that the server request will succeed, and rolling back if it fails",
        explanation: "Optimistic updates deliver instant perceived responsiveness for high-confidence actions (e.g. liking, bookmarking, toggling).",
        difficulty: "medium",
        points: 10,
        active: true,
      },
      {
        id: "q-fs-2",
        assessmentId: "assess-fullstack-integration",
        skillId: "fullstack-integration",
        question: "How should authentication tokens be transmitted from a Single Page Application to an API backend?",
        options: [
          "In the URL query string (?token=xyz)",
          "In the Authorization header as a Bearer token or in an HttpOnly, Secure, SameSite cookie",
          "In the HTML title tag",
          "In public GitHub repositories"
        ],
        correctAnswer: "In the Authorization header as a Bearer token or in an HttpOnly, Secure, SameSite cookie",
        explanation: "Bearer headers and HttpOnly cookies prevent token leakage via server logs and browser history.",
        difficulty: "easy",
        points: 10,
        active: true,
      },
      {
        id: "q-fs-3",
        assessmentId: "assess-fullstack-integration",
        skillId: "fullstack-integration",
        question: "What is the primary role of a Reverse Proxy (e.g. Nginx, Vercel Edge) in a full-stack architecture?",
        options: [
          "To replace the React framework",
          "To sit in front of backend servers, routing requests, terminating SSL/TLS, serving static assets, and managing caching/load balancing",
          "To edit database records directly",
          "To compile TypeScript in the browser"
        ],
        correctAnswer: "To sit in front of backend servers, routing requests, terminating SSL/TLS, serving static assets, and managing caching/load balancing",
        explanation: "Reverse proxies provide security isolation, centralized routing, compression, and load balancing.",
        difficulty: "medium",
        points: 10,
        active: true,
      },
      {
        id: "q-fs-4",
        assessmentId: "assess-fullstack-integration",
        skillId: "fullstack-integration",
        question: "What is a 'Race Condition' in frontend data fetching and how can it be prevented?",
        options: [
          "When two users log in at the same second",
          "When an earlier network request finishes AFTER a later request, overwriting newer state with stale data; prevented with AbortController or ignore flags",
          "When CSS styles load faster than HTML",
          "When a loop runs out of memory"
        ],
        correctAnswer: "When an earlier network request finishes AFTER a later request, overwriting newer state with stale data; prevented with AbortController or ignore flags",
        explanation: "Unsynchronized async responses can resolve out-of-order, corrupting client state unless stale requests are aborted or ignored.",
        difficulty: "hard",
        points: 10,
        active: true,
      },
      {
        id: "q-fs-5",
        assessmentId: "assess-fullstack-integration",
        skillId: "fullstack-integration",
        question: "Why should environment variables used strictly on the server (e.g. DATABASE_URL, FIREBASE_ADMIN_KEY) never have 'NEXT_PUBLIC_' prefix in Next.js?",
        options: [
          "Next.js will refuse to build",
          "The NEXT_PUBLIC_ prefix embeds the variable value directly into the public client-side JavaScript bundle downloaded by every browser",
          "It slows down server startup",
          "It converts strings to numbers"
        ],
        correctAnswer: "The NEXT_PUBLIC_ prefix embeds the variable value directly into the public client-side JavaScript bundle downloaded by every browser",
        explanation: "NEXT_PUBLIC_ prefixes instruct the bundler to inline the secret into client JS, exposing backend infrastructure.",
        difficulty: "easy",
        points: 10,
        active: true,
      },
      {
        id: "q-fs-6",
        assessmentId: "assess-fullstack-integration",
        skillId: "fullstack-integration",
        question: "How should a full-stack application handle network disconnection states?",
        options: [
          "Crash the application immediately",
          "Display non-intrusive offline banners, preserve unsaved form drafts in memory or IndexedDB, and disable submit buttons gracefully",
          "Delete the user profile",
          "Redirect to a 404 page"
        ],
        correctAnswer: "Display non-intrusive offline banners, preserve unsaved form drafts in memory or IndexedDB, and disable submit buttons gracefully",
        explanation: "Resilient applications monitor navigator.onLine and preserve draft states during transient outages.",
        difficulty: "medium",
        points: 10,
        active: true,
      },
      {
        id: "q-fs-7",
        assessmentId: "assess-fullstack-integration",
        skillId: "fullstack-integration",
        question: "What is End-to-End (E2E) testing (e.g. using Playwright) testing in a full-stack web application?",
        options: [
          "Testing a single JavaScript function in isolation",
          "Testing real user workflows simulating browser clicks, network calls, server processing, and database mutations from start to finish",
          "Auditing CSS file size",
          "Checking git commit messages"
        ],
        correctAnswer: "Testing real user workflows simulating browser clicks, network calls, server processing, and database mutations from start to finish",
        explanation: "E2E tests validate complete user journeys across the full system stack (frontend, network, backend, database).",
        difficulty: "easy",
        points: 10,
        active: true,
      },
    ],
  },
];
